steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'getPlaquePageUrlsFromOhtIndexPage', '--trigger-topic', 'plaqueIndexPagesToSpider', '--runtime', 'nodejs8']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'getPlaqueDataFromOhtPage', '--trigger-topic', 'plaquePagesToScrape', '--runtime', 'nodejs8']
