steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then gcloud functions deploy getPlaqueDataFromOhtPage --runtime nodejs8 --trigger-http; else exit 0; fi
